export const transactiondata = {
    "data": [
        {
            "amount": "₹10.00",
            "type": "gifts_sent",
            "count": 0,
            "order_id": "2000015656641965",
            "created_at": "14 Nov,2018 10:14 PM",
            "display_name": "Gift Card Sent",
            "detail_display_name": "Gift Card Sent",
            "retailer_name": null,
            "receiver_name":"Hello",
            "receiver_no": "1234567890",
            "personal_message": "Wish you a merry chritsmas, wish you a merry chritsmas and a very happy new year! :)"
        },
        {
            "amount": "₹10.00",
            "type": "gifts_sent",
            "count": 0,
            "order_id": "2000015651112864",
            "created_at": "14 Nov,2018 10:14 PM",
            "display_name": "Gift Card Sent",
            "detail_display_name": "Gift Card Sent",
            "retailer_name": null,
            "receiver_name":"Hello",
            "receiver_no": "1234567890",
            "personal_message": "Wish you a merry chritsmas, wish you a merry chritsmas and a very happy new year! :)"
        },
        {
            "amount": "₹200.00",
            "type": "gifts_sent",
            "count": 0,
            "order_id": "2000015658919983",
            "created_at": "13 Nov,2018 9:45 PM",
            "display_name": "Gift Card Cancelled",
            "detail_display_name": "Gift Card Cancelled",
            "retailer_name": null,
            "receiver_name":"Hello",
            "receiver_no": "1234567890",
            "personal_message": "Wish you a merry chritsmas, wish you a merry chritsmas and a very happy new year! :)"
        },
        {
            "amount": "₹10.00",
            "type": "gifts_sent",
            "count": 0,
            "order_id": "2000015653605586",
            "created_at": "4 Nov,2018 11:41 PM",
            "display_name": "Gift Card Redeemed",
            "detail_display_name": "Gift Card Redeemed",
            "retailer_name": null,
            "receiver_name":"Hello",
            "receiver_no": "1234567890",
            "personal_message": "Wish you a merry chritsmas, wish you a merry chritsmas and a very happy new year! :)"
        },
        {
            "amount": "₹365.00",
            "type": "gifts_sent",
            "count": 0,
            "order_id": "2000015652095563",
            "created_at": "29 Oct,2018 11:03 PM",
            "display_name": "Gift Card Sent",
            "detail_display_name": "Gift Card Sent",
            "retailer_name": null,
            "receiver_name":"Hello",
            "receiver_no": "1234567890",
            "personal_message": "Wish you a merry chritsmas, wish you a merry chritsmas and a very happy new year! :)"
        },
        {
            "amount": "₹9.00",
            "type": "gifts_sent",
            "count": 0,
            "order_id": "2000015655417552",
            "created_at": "29 Oct,2018 1:18 PM",
            "display_name": "Gift Card Redeemed",
            "detail_display_name": "Gift Card Redeemed",
            "retailer_name": null,
            "receiver_name":"Hello",
            "receiver_no": "1234567890",
            "personal_message": "Wish you a merry chritsmas, wish you a merry chritsmas and a very happy new year! :)"
        },
        {
            "amount": "₹9.00",
            "type": "gifts_sent",
            "count": 0,
            "order_id": "2000015653865790",
            "created_at": "29 Oct,2018 1:18 PM",
            "display_name": "Gift Card Redeemed",
            "detail_display_name": "Gift Card Redeemed",
            "retailer_name": null,
            "receiver_name":"Hello",
            "receiver_no": "1234567890",
            "personal_message": "Wish you a merry chritsmas, wish you a merry chritsmas and a very happy new year! :)"
        },
        {
            "amount": "₹9.00",
            "type": "gifts_sent",
            "count": 0,
            "order_id": "2000015656989739",
            "created_at": "29 Oct,2018 1:18 PM",
            "display_name": "Gift Card Sent",
            "detail_display_name": "Gift Card Sent",
            "retailer_name": null,
            "receiver_name":"Hello",
            "receiver_no": "1234567890",
            "personal_message": "Wish you a merry chritsmas, wish you a merry chritsmas and a very happy new year! :)"
        },
        {
            "amount": "₹9.00",
            "type": "gifts_sent",
            "count": 0,
            "order_id": "2000015659030389",
            "created_at": "29 Oct,2018 1:18 PM",
            "display_name": "Gift Card Sent",
            "detail_display_name": "Gift Card Sent",
            "retailer_name": null,
            "receiver_name":"Hello",
            "receiver_no": "1234567890",
            "personal_message": "Wish you a merry chritsmas, wish you a merry chritsmas and a very happy new year! :)"
        },
        {
            "amount": "₹10.55",
            "type": "gifts_sent",
            "count": 0,
            "order_id": "2000015658496317",
            "created_at": "26 Oct,2018 3:47 PM",
            "display_name": "Gift Card Redeemed",
            "detail_display_name": "Gift Card Redeemed",
            "retailer_name": null,
            "receiver_name":"Hello",
            "receiver_no": "1234567890",
            "personal_message": "Wish you a merry chritsmas, wish you a merry chritsmas and a very happy new year! :)"
        }
    ]
}
